### ISSUE TITLE
Group services depending on function, purpose or nature

### ISSUE THREAD

**Issue by ericlp** [cthit/findIT#44]
As of today there are 21 services visible on findit.chalmers.it which fills my entire screen and some more. To more easily navigate among these cards/link I think it would be favourable to group them with similar cards. A proposal can be seen below.

Hubben related services:
 * Bookit
 * hubbot
 * hueIT
 * singIT
 * VulcanTV
 * SuggestIT

Other Websites:
 * BussIT
 * Chalmers.it
 * eatIT
 * HowTo
 * LinkIT
 * mat
 * sannes
 * songbook

Various Links:
 * findIT
 * GDPR
 * Github
 * IRC tutorial
 * IT event calendar
 * slack
 * wikITpedia

**Comment by antoneekstrom** [comment]
Hello, how would you group the cards? My first thought is to put the cards under different sections vertically on the page. I was also thinking it would be cool to be able to filter the cards by category.

**Comment by ericlp** [comment]
I would prefer having rows for the categories and a stickied nav-section to the left. The section could have a link to each category which when clicked focuses on the header for that category.

**Comment by antoneekstrom** [comment]
Ah right, I think that was about what I meant to say. A side navigation is a good idea!

**Comment by antoneekstrom** [comment]
I've made some changes to add this functionality on a clone of the repo. Do I make a fork in order to add a pull request? I am unsure of how you usually do this :)
edit: I have now discovered I can make a pull request from a branch so I will attempt that instead.
edit: Nevermind, I can't push to the repository so that won't work

**Comment by simonengstrm** [comment]
I see this issue has already been linked to a pull request by @zimbosaurus. I'd just like to shed light on an idea i had using the service:

I feel like it's hard to group the services in only three categories, maybe some sort of "tagging" system would be optimal? Just a thought. Tags could be: "Tool", "Social, "Food, "Hubben", "Link" etc.
Edit: Forgot to add that tags then can be filtered to see all tools with a certain tag.

**Comment by Hoidi** [comment]
That sounds pretty nice. Sort of like @ericlp has done with SongBook

**Comment by simonengstrm** [comment]
Yes, pretty much, but also allow services to have several tags. Otherwise its kinda like just having more categories.
